export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SET_ISSUCESS = 'SET_ISSUCESS';
export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_PRODUCT_EDITING = 'SET_PRODUCT_EDITING';